version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9000
